name: py-backapp

services:
  server:
    build:
      context: ./
      dockerfile: ./server/server.Dockerfile
    environment:
      PORT: 1234
    ports:
      - "1234:1234"
    networks:
      - backapp-net

networks:
  backapp-net: